name: Deploy Cloud Resume Challenge

on:
  push:
    branches:
      - main

# Required for OIDC AWS authentication
permissions:
  id-token: write
  contents: read

jobs:
  deploy-infra:
    name: Deploy Infrastructure
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        
      - name: Configure AWS Credentials with OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::983401047977:role/github-actions-cloud-resume-role
          aws-region: eu-north-1

      - name: Terraform Init
        working-directory: ./terraform
        run: terraform init

      - name: Terraform Validate
        working-directory: ./terraform
        run: terraform validate

      - name: Terraform Apply
        working-directory: ./terraform
        run: terraform apply -auto-approve
